"""phase 1: weighbridge tickets

Revision ID: 23b1b4ecb8d9
Revises: faf06f89c6a6
Create Date: 2026-08-18 10:45:45.751992

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "23b1b4ecb8d9"
down_revision: Union[str, None] = "faf06f89c6a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weighbridge_tickets",
        sa.Column("organization_unit_id", sa.Uuid(), nullable=True),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("ticket_number", sa.String(length=50), nullable=False),
        sa.Column(
            "ticket_type",
            sa.Enum("INBOUND", "OUTBOUND", name="weighbridge_ticket_type"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("OPEN", "COMPLETED", "CANCELLED", name="weighbridge_ticket_status"),
            nullable=False,
        ),
        sa.Column("vehicle_number", sa.String(length=20), nullable=False),
        sa.Column("driver_name", sa.String(length=100), nullable=True),
        sa.Column("party_name", sa.String(length=200), nullable=True),
        sa.Column("material_description", sa.String(length=200), nullable=False),
        sa.Column("first_weight", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("first_weighed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("second_weight", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("second_weighed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("net_weight", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_unit_id"], ["organization_units.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "ticket_number", name="uq_weighbridge_ticket_number"),
    )
    op.create_index(
        op.f("ix_weighbridge_tickets_organization_unit_id"),
        "weighbridge_tickets",
        ["organization_unit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weighbridge_tickets_tenant_id"), "weighbridge_tickets", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weighbridge_tickets_tenant_id"), table_name="weighbridge_tickets")
    op.drop_index(
        op.f("ix_weighbridge_tickets_organization_unit_id"), table_name="weighbridge_tickets"
    )
    op.drop_table("weighbridge_tickets")
    # ### end Alembic commands ###
