"""phase 3: production entries

Revision ID: 73618eeb581f
Revises: 23b1b4ecb8d9
Create Date: 2026-08-18 15:08:56.410976

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "73618eeb581f"
down_revision: Union[str, None] = "23b1b4ecb8d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "production_entries",
        sa.Column("organization_unit_id", sa.Uuid(), nullable=True),
        sa.Column("raw_material_unit_id", sa.Uuid(), nullable=False),
        sa.Column("entry_number", sa.String(length=50), nullable=False),
        sa.Column("production_date", sa.Date(), nullable=False),
        sa.Column("shift", sa.Enum("DAY", "NIGHT", name="production_shift"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "SUBMITTED", "CANCELLED", name="production_entry_status"),
            nullable=False,
        ),
        sa.Column("raw_material_description", sa.String(length=200), nullable=False),
        sa.Column("raw_material_quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_unit_id"], ["organization_units.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["raw_material_unit_id"], ["units.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "entry_number", name="uq_production_entry_number"),
    )
    op.create_index(
        op.f("ix_production_entries_organization_unit_id"),
        "production_entries",
        ["organization_unit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_production_entries_tenant_id"), "production_entries", ["tenant_id"], unique=False
    )
    op.create_table(
        "production_outputs",
        sa.Column("production_entry_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("product_description", sa.String(length=200), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["production_entry_id"], ["production_entries.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_production_outputs_production_entry_id"),
        "production_outputs",
        ["production_entry_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_production_outputs_production_entry_id"), table_name="production_outputs"
    )
    op.drop_table("production_outputs")
    op.drop_index(op.f("ix_production_entries_tenant_id"), table_name="production_entries")
    op.drop_index(
        op.f("ix_production_entries_organization_unit_id"), table_name="production_entries"
    )
    op.drop_table("production_entries")
    # ### end Alembic commands ###
